# Generated by Django 5.0.6 on 2024-06-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_individual_organization_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.partner'),
        ),
    ]
