# Generated by Django 5.0.6 on 2024-06-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_organization_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(null=True),
        ),
    ]
